class Links:

    HOST = "https://demoqa.com"
    TEXT_BOX_PAGE = f"{HOST}/text-box"
    CHECK_BOX_PAGE = f"{HOST}/checkbox"
    RADIO_BUTTON_PAGE = f"{HOST}/radio-button"
    WEB_TABLES_PAGE = f"{HOST}/webtables"
    BUTTONS_PAGE = f"{HOST}/buttons"
    LINKS_PAGE = f"{HOST}/links"
    BROKEN_LINKS_IMAGES_PAGE = f"{HOST}/broken"
    UPLOAD_AND_DOWNLOAD_PAGE = f"{HOST}/upload-download"
    DYNAMIC_PROPERTIES_PAGE = f"{HOST}/dynamic-properties"
    PRACTICE_FORM_PAGE = f"{HOST}/automation-practice-form"
    BROWSER_WINDOWS_PAGE = f"{HOST}/browser-windows"
    ALERTS_PAGE = f"{HOST}/alerts"
    FRAMES_PAGE = f"{HOST}/frames"
    NESTED_FRAMES_PAGE = f"{HOST}/nestedframes"
    MODAL_DIALOGS_PAGE = f"{HOST}/modal-dialogs"
    # PERSONAL_PAGE = f"{HOST}/pim/viewPersonalDetails/empNumber/7"